openapi: 3.0.3
info:
  title: Pet API
  description: A simple API to get a random list of pets.
  version: 1.0.0

paths:
  /pets:
    get:
      summary: Get a list of pets
      operationId: getPets
      responses:
        '200':
          description: A list of pets.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
              example:
              - id: 1
                name: "Fluffy"
                photoUrls:
                - "https://example.com/fluffy.jpg"
              - id: 2
                name: "Buddy"
                photoUrls:
                - "https://example.com/buddy.jpg"
components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: integer
          format: int64
          x-faker: random.number
        name:
          type: string
          x-faker: name.firstName
        photoUrls:
          type: array
          items:
            type: string
            x-faker: image.imageUrl
